### ISSUE TITLE
Valida todos os campos ao encontrar o 1º erro

### ISSUE THREAD

**Issue by halley-com-br** [Innercodebr/InnerFormValidation#2]
Sempre q um campo nao corresponde e lança erro outros campos do formulario q ainda nem receberam o foco recebem a class de erro. Tem como resolver?

**Comment by zonaro** [comment]
Vamos adicionar isso as próximas atualizações

**Comment by zonaro** [comment]
@halley-com-br atualizei o master, valida se agora está tudo certo por favor?

**Comment by halley-com-br** [comment]
Meu amigo, me desculpa a demora pelo feedback. Ficou simplesmente ótimo. Te agradeço pela rápida resposta bem como a solução. Em 15 anos de programação foi um dos melhores compilados de script pra validação de fórmulário que encontrei, já uso em todos os meus projetos. Espero poder contribuir mais ainda em breve. Obg. Abraço!

**Comment by zonaro** [comment]
Eu que agradeço amigo, faço o possível pra entregar algo que seja útil pra comunidade.
